Models/Mission.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OXG.CRM_System.Models
{
    public class Mission
    {
        public int Id { get; set; }

        public string MissionText { get; set; }

        public string Picture
        {
            get
            {
                switch (MissionType)
                {
                    case "Звонок":
                        return "/images/icons/Phone.png";
                    case "Email":
                        return "/images/icons/Email.png";
                    case "Договор":
                        return "/images/icons/Note.png";
                    case "Утверждение макета":
                        return "/images/icons/Copy.png";
                    case "Создание задачи":
                        return "/images/icons/Copy.png";
                    case "Указать артиста":
                        return "/images/icons/Playboy.png";
                    case "Указать техника":
                        return "/images/icons/Custom.png";
                    case "Заявка":
                        return "/images/icons/VK.png";
                    case "Автоматическая заявка":
                        return "/images/icons/Android.png";
                    default:
                        return "/images/icons/Check Box.png";
                }
            }
        }

        public DateTime DeadLine { get; set; }

        public DateTime CreatedDate { get; set; }

        public TimeSpan LeftTime { get { return DeadLine - DateTime.Now; } } 

        public string Status { get; set; }

        public string MissionType { get; set; }

        public bool IsFailed { get; set; }

        public string EmployeerId { get; set; }
        public User Employeer { get; set; }

        public int EventId { get; set; }
        public Event Event { get; set; }

        public string GetLeftTime()
        {
            var s =$"{LeftTime.Hours} часов {LeftTime.Minutes} минут";
            return s;
        }
    }
}

Controllers/MissionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OXG.CRM_System.Data;
using OXG.CRM_System.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace OXG.CRM_System.Controllers
{
    /// <summary>
    /// Контроллер отвечающий за задачи пользователей
    /// </summary>
    [Authorize]
    public class MissionController : Controller
    {
        private readonly CRMDbContext db;
        private readonly IWebHostEnvironment _appEnvironment;
        public MissionController(CRMDbContext context, IWebHostEnvironment appEnvironment)
        {
            db = context;
            _appEnvironment = appEnvironment;
        }

        /// <summary>
        /// ВОзвращает представление создания нового мероприятия после заявки
        /// </summary>
        /// <returns></returns>
        public IActionResult NewEvent()
        {
            ViewBag.EventTypes = StaticValues.GetEventTypes();
            ViewBag.FromRequest = true;
            return RedirectToAction("New", "Events", new { FromRequest = true });
        }

        /// <summary>
        /// Создаёт новую заявку для текущего пользователя
        /// </summary>
        /// <param name="RequestText">Текст заявки</param>
        /// <returns></returns>
        public async Task<IActionResult> NewRequest(string RequestText)
        {
            var request = new Mission
            {
                CreatedDate = DateTime.Now,
                DeadLine = DateTime.Now.AddDays(1),
                MissionText = RequestText,
                MissionType = "Заявка",
                Status = "Создано",
                Event = await db.Events.Where(e => e.Name == "TempEvent").FirstOrDefaultAsync(),
                Employeer = await db.Managers.Where(m => m.Email == User.Identity.Name).FirstOrDefaultAsync()
            };
            await db.Missions.AddAsync(request);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Manager");
        }

        /// <summary>
        /// Возвращает представление для отклонения заявки
        /// </summary>
        /// <param name="id">id заявки</param>
        /// <returns></returns>
        public IActionResult Reject(int id)
        {
            ViewBag.mId = id;
            ViewBag.RejectCauses = new SelectList(StaticValues.RejectCauses);
            return View();
        }

        /// <summary>
        /// Закрывает заявку
        /// </summary>
        /// <param name="RejPrin">Причина отклонения заявки</param>
        /// <param name="id">id заявки</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Reject(string RejPrin, int id)
        {

            var mission = await db.Missions.Where(m => m.Id == id).FirstOrDefaultAsync();
            mission.Status = "Закрыто";
            mission.MissionText += $"| Заявка отклонена, причина: {RejPrin}";
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Manager");
        }

        /// <summary>
        /// Увеличивает время на обработку заявки
        /// </summary>
        /// <param name="Id">Id заявки</param>
        /// <param name="postHour">Кол-во часов на которое откладывается дедлайн</param>
        /// <returns></returns>
        public async Task<IActionResult> Postpound(int Id, int postHour)
        {
            var mission = await db.Missions.Where(m => m.Id == Id).FirstOrDefaultAsync();
            mission.DeadLine = mission.DeadLine.AddHours(postHour);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Manager");
        }

        /// <summary>
        /// Возвращает представление для действий над заданием 
        /// </summary>
        /// <param name="id">ID задания</param>
        /// <returns></returns>
        public async Task<IActionResult> Close(int id)
        {
            var mission = await db.Missions.Include(e => e.Employeer).Include(e => e.Event).Where(e => e.Id == id).FirstOrDefaultAsync();
            var type = mission.MissionType;
            if (type == "Заявка" || type == "Автоматическая заявка")
            {
                return View("CloseRequest", mission);
            }
            return RedirectToAction("View", "Events", new { id = mission.EventId, missionId = mission.Id });
        }
    }
}

Views/Mission/CloseRequest.cshtml
@model OXG.CRM_System.Models.Mission
@{
    ViewData["Title"] = "Заявка";
}

<div class="jumbotron">
    <h1 class="display-3">@Model.MissionType</h1>
    <h3 class="lead">@Html.Raw(Model.MissionText)</h3>
    <hr class="my-4">
    <div class="row">
        <div class="col-lg-6">
            <button type="button" class="btn btn-primary btn-lg btn-block n" data-toggle="modal" data-target="#ModalCenter">
                Отложить
            </button>
        </div>

        <div class="col-lg-6"><a asp-action="Reject" asp-controller="Mission" asp-route-id="@Model.Id" class="btn btn-warning btn-lg btn-block">Отклонить</a></div>
    </div>
    <br />
    <div class="row"></div>
    <a asp-action="NewEvent" asp-controller="Mission" class="btn btn-success btn-lg btn-block">Создать новое мероприятие</a>
</div>



<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <form asp-action="Postpound" method="post" >
            <div class="modal-content" style="width:550px">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Отложить заявку</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="exampleInputEmail1">Отложить на</label>
                        <input type="number" class="form-control" id="exampleInputEmail1" name="postHour">
                        <small id="emailHelp" class="form-text text-muted">Введите кол-во часов на которое необходимо отложить заявку.</small>
                        <input hidden value="@Model.Id" name="Id"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Отправить" />
                </div>
            </div>
        </form>
    </div>
</div>

Views/Mission/NewRequest.cshtml
@model OXG.CRM_System.Models.Mission
@{
    ViewData["Title"] = "NewRequest";
}

<h1>Создать заявку</h1>

<form asp-action="newRequest" method="post">
    <div></div>
</form>

Views/Mission/Reject.cshtml
@{
    ViewData["Title"] = "Отклонить";
}

<h1>Отклонить</h1>

<form asp-action="Reject">
    <div class="form-group">
        <label for="Input">Причина отклонения</label>
        @*<input name="RejPrin" type="" class="form-control" id="Input" placeholder="">*@
        <select asp-items="@ViewBag.RejectCauses" name="RejPrin" class="custom-select"></select>
        <small id="emailHelp" class="form-text text-muted">Выберите причину по которой заявка была отклонена</small>
        <input type="submit" class="btn btn-primary" value="Отправить"/>
        <input hidden name="id" value="@ViewBag.mId" />
    </div>
</form>